/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003824",
        "outline-variant": "#464554",
        "on-tertiary-fixed": "#301400",
        "secondary-container": "#00a572",
        "inverse-surface": "#e5e1e4",
        "surface-container": "#201f21",
        "surface-container-highest": "#353437",
        "surface-container-high": "#2a2a2c",
        "on-surface-variant": "#c7c4d7",
        "on-tertiary-fixed-variant": "#703700",
        "surface-tint": "#c0c1ff",
        "tertiary": "#ffb783",
        "on-primary-fixed": "#07006c",
        "surface-variant": "#353437",
        "on-tertiary": "#4f2500",
        "on-tertiary-container": "#452000",
        "surface-bright": "#39393b",
        "tertiary-fixed-dim": "#ffb783",
        "surface-dim": "#131315",
        "surface-container-lowest": "#0e0e10",
        "primary-fixed-dim": "#c0c1ff",
        "primary-container": "#8083ff",
        "on-error": "#690005",
        "outline": "#908fa0",
        "surface-container-low": "#1c1b1d",
        "on-primary-container": "#0d0096",
        "secondary-fixed": "#6ffbbe",
        "on-secondary-container": "#00311f",
        "error-container": "#93000a",
        "primary": "#c0c1ff",
        "on-background": "#e5e1e4",
        "inverse-primary": "#494bd6",
        "inverse-on-surface": "#313032",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#005236",
        "surface": "#131315",
        "tertiary-container": "#d97721",
        "tertiary-fixed": "#ffdcc5",
        "on-error-container": "#ffdad6",
        "background": "#131315",
        "on-surface": "#e5e1e4",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary": "#4edea3",
        "on-primary": "#1000a9",
        "primary-fixed": "#e1e0ff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "stack-xs": "4px",
        "container-max": "1200px",
        "stack-md": "16px",
        "gutter": "24px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "headline-lg": ["Outfit"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Outfit"],
        "mono-label": ["JetBrains Mono"],
        "headline-sm": ["Outfit"],
        "mono-data": ["JetBrains Mono"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-label": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "mono-data": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
